### ISSUE TITLE
Battery indicator

### ISSUE THREAD

**Issue by koluris** [ouija/Surface4Pro-i7-6650U-Hackintosh#1]
Hello, great work overall. Does the battery indicator work for you using everything as-is on your repo?

**Comment by ouija** [comment]
Apologies for the late reply, but from I can remember I don't think the battery status did work correctly, or I hadn't even ventured that far to make it so.

Because there isn't any IPTS driver support for the Surface under macOS, I abandoned my interest in pursuing this project any further.
